# This workflow will deploy the project to AWS EC2

name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout the files
      uses: actions/checkout@v4
  
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: "ec2-13-212-145-130.ap-southeast-1.compute.amazonaws.com"
        REMOTE_USER: "ubuntu"
        TARGET: "/home/ubuntu/BlossomzBot"

    - name: SSH into EC2, Install Dependencies, Run main.py
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: "ec2-13-212-145-130.ap-southeast-1.compute.amazonaws.com"
        REMOTE_USER: "ubuntu"
        TARGET: "/home/ubuntu/BlossomzBot"
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key -tt ${REMOTE_USER}@${REMOTE_HOST} '
            cd /home/ubuntu/BlossomzBot &&
            pip3 install -r requirements.txt &&
            sudo systemctl restart BlossomzBot.service
            '
