error_messages = {
    "01": "There was a database-related error when checking whether the new guest already exists in the server.",
    "02": "There was a api-related error when trying to create a new entry in the spreadsheet.",
    "03": "There was a database-related error when trying to delete a member.",
    "04": "There was an error with the kick_nicely command when trying to send a message to the user. They may have direct messages disabled",
    "05": "There was an error when trying to send a welcome message to the user. They may have direct messages disabled",
}

kick_message = "Hello!\n\nAs part of cleaning up our discord server, you have unfortuately been kicked from the Blossomz discord due to long periods of inactivity (whether it is ingame or taking part in the community). If you have characters in our guilds, we have kicked them as well.\n\nHowever, you are very welcome to reach out and rejoin us again in future if you were to play actively and would like to be part of Blossomz again!"

welcome_message = "Hi! Welcome to Blossomz, we're happy to have you join us! :blush:\n\nI am here to help introduce you a bit to the guild as well as the discord server. You have been given either the 'Member' or 'Best Friend' role, which means that you can enjoy all the privileges in the server. \n\n'Members' are people who have joined our Blossomz guild ingame. 'Best Friends' are people who are not in our guild but actively participate in our community, mainly people from the Thaemine server. 'Friends' and 'Guests' have limited privileges in our discord server, for example 'Guests' can only view the voice chat channels. As a Member / Best Friend, you are able to react to roles in the https://discord.com/channels/1089523190843314306/1091508527475982507 channel where you can sign up to be pinged for various things, most importantly for raids.\n\nIf you are comfortable, do take part in conversations in the general chat channels and express yourself, or if you want to hop on to vc to chat, you are welcome to do so! For raids, we mostly use https://discord.com/channels/1089523190843314306/1090940581003403284, often using the respective raid pings as well. When people post here, they are often not scheduled and are more on a ad hoc basis, usually to fill spots for reclear runs.\n\nRaids that are scheduled and organised are usually done in https://discord.com/channels/1089523190843314306/1108936913626337322 for prog / learning runs. Do make a post or comment on existing ones if you are interested in any of the raids and want to join / find people to help out, there are many helpful people around who would join! We also use https://discord.com/channels/1089523190843314306/1090949266710724658 sometimes to organise runs using the raid-helper tool.\n\nLastly, if you haven't already please introduce yourself in https://discord.com/channels/1089523190843314306/1090933136327712818 and if you are a Member, apply to Blossomz ingame when you are able to!\n\nBtw don't reply to me, I am a bot :sweat:"

# Dev
# welcome_message = "Hi! Welcome to Blossomz, we're happy to have you join us! :blush:\n\nI am here to help introduce you a bit to the guild as well as the discord server. You have been given either the 'Member' or 'Best Friend' role, which means that you can enjoy all the privileges in the server. \n\n'Members' are people who have joined our Blossomz guild ingame. 'Best Friends' are people who are not in our guild but actively participate in our community, mainly people from the Thaemine server. 'Friends' and 'Guests' have limited privileges in our discord server, for example 'Guests' can only view the voice chat channels. As a Member / Best Friend, you are able to react to roles in the https://discord.com/channels/1221723231862657055/1221723232831279141 channel where you can sign up to be pinged for various things, most importantly for raids.\n\nIf you are comfortable, do take part in conversations in the general chat channels and express yourself, or if you want to hop on to vc to chat, you are welcome to do so! For raids, we mostly use https://discord.com/channels/1221723231862657055/1221723233389379680, often using the respective raid pings as well. When people post here, they are often not scheduled and are more on a ad hoc basis, usually to fill spots for reclear runs.\n\nRaids that are scheduled and organised are usually done in https://discord.com/channels/1221723231862657055/1230604395977117767 for prog / learning runs. Do make a post or comment on existing ones if you are interested in any of the raids and want to join / find people to help out, there are many helpful people around who would join! We also use https://discord.com/channels/1221723231862657055/1221723233389379682 sometimes to organise runs using the raid-helper tool.\n\nLastly, if you haven't already please introduce yourself in https://discord.com/channels/1221723231862657055/1221723232831279143 and if you are a Member, apply to Blossomz ingame when you are able to!\n\nBtw don't reply to me, I am a bot :sweat:"
